name: _DEBUG

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity (internal only)
        run: |
          echo "Hi from ${{ github.ref }}"
          git --version
          uname -a
# bump 2025-10-09 10:44:46
# bump 2025-10-09 10:45:14
