name: _SMOKE

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SMOKE OK on ${{ github.ref }}"
          git --version
          uname -a
